name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - v*
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
jobs:
  release-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RELEASE_ZIP_FILENAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create release ZIP file
        run: |-
          mkdir ${{ github.event.repository.name }}
          rm -rf .git .github .gitignore .dockerignore Dockerfile CONTRIBUTING.md pyrightconfig.json
          mv * ${{ github.event.repository.name }} || true
          zip -r $RELEASE_ZIP_FILENAME ${{ github.event.repository.name }}
      - name: Release on GitHub
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          generate_release_notes: true
          files: ${{ env.RELEASE_ZIP_FILENAME }}
          body: |-
            Docker Image: [${{ env.DOCKER_IMAGE_NAME }}](https://${{ env.DOCKER_IMAGE_NAME }})
  release-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Sign into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/i386,linux/arm
          push: true
          provenance: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.ref_name }},${{ env.DOCKER_IMAGE_NAME }}:latest
